eax_employee_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('employee_leave.urls') ),
    path('', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee_leave/urls.py
from django.urls import path
from .views import homepage, leave, employee, ProfileView, CustomPasswordChangeView, supervisor_change_status, supervisor_approve, supervisor_cancel

urlpatterns = [
    path('', homepage, name='home'),
    path('leave/', leave, name='leave'),
    path('employee/', employee, name='employee'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('supervisor_leaves/', supervisor_change_status, name='supervisor_leaves'),
    path('supervisor_approve/<int:pk>/', supervisor_approve, name='supervisor_approve'),
    path('supervisor_cancel/<int:pk>/', supervisor_cancel, name='supervisor_cancel'),
    path("change_password/", CustomPasswordChangeView.as_view(), name="change_password"),
]

employee_leave/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class CustomUser(AbstractUser):
    first_login = models.BooleanField(default=True)

    def __str__(self):
        return self.username

LEAVE_TYPE = (
    ('paid_leave', 'Paid Leave'),
    ('sick_leave', 'Sick Leave'),
    ('marternity_leave', 'Marternity Leave'),
    ('parternity_leave', 'Parternity Leave'),
    ('sabbatical_leave', 'Sabbatical Leave'),
)

STATUS = (
    ('pending', 'Pending'),
    ('cancelled', 'Cancelled'),
    ('approved', 'Approved'),
)

SUPERVISOR_STATUS = (
    ('pending', 'Pending'),
    ('cancelled', 'Cancelled'),
    ('approved', 'Approved'),
)



GENDER = (
    ('male', 'Male'),
    ('female', 'Female'),
)

class EmployeeAttachment(models.Model):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE, related_name='attachments', null=True, blank=False)
    attachment_name = models.CharField(max_length=200)
    file = models.FileField(upload_to='attachment/')


class Department(models.Model):
    department_name = models.CharField(max_length=200)
    department_head = models.OneToOneField("Employee",on_delete=models.SET_NULL, related_name="department_supervisor",null=True, blank=True)

    def __str__(self):
        return str(self.department_name)
    
    

class Employee(models.Model):
    first_name = models.CharField(max_length=200, null=True, blank=False)
    last_name = models.CharField(max_length=200, null=True, blank=False)
    email = models.EmailField(null=True, blank=False)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    phone_number = models.CharField(max_length=15)
    sex = models.CharField(max_length=7,choices=GENDER, blank=True, null=True)
    salary = models.IntegerField()
    position = models.CharField(max_length=200)
    hire_date = models.DateField(null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=False)
    department = models.ForeignKey(Department,on_delete=models.SET_NULL, related_name="in_department",null=True, blank=False)
    rssb_id = models.CharField(max_length=200, null=True, blank=False)
    allowed_leave = models.IntegerField(default=18, blank=True, null=True)
    taken_leave = models.IntegerField(default=0, blank=True, null=True)
    initial_leave = models.IntegerField(default=18, blank=True, null=True)
    photo = models.ImageField(upload_to='profile/',blank=True, null=True)

    def __str__(self):
        return str(self.first_name)

class NextOfKeen(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='next_of_keens', null=True)
    next_of_keen_first_name = models.CharField(max_length=100)
    next_of_keen_last_name = models.CharField(max_length=100)
    next_of_keen_phone_number = models.CharField(max_length=100)

class Leave(models.Model):
    employee = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    leave_type = models.CharField(max_length=30, choices=LEAVE_TYPE)
    leave_date = models.DateField()
    return_date = models.DateField()
    status = models.CharField(max_length=30, choices=STATUS, default='pending', blank=True, null=True)
    supervisor_status = models.CharField(max_length=30, choices=SUPERVISOR_STATUS, default='pending', blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    

    def __str__(self):
        return f'{self.employee} - {self.leave_date}'







        

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Dashboard - EAX</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/EAXLogo.png' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet"> 
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar navbar-dark">
                <a href="{% url 'home' %}" class="navbar-brand mx-4 mb-3">
                    <!-- <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>Dashboard</h3> -->
                    <h3 class="text-primary"><img src="{% static 'img/EAXLogo.png' %}" class="img-fluid bg-white" alt=""></h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        {% if request.user.employee.photo %}
                        <img class="rounded-circle" src="{{request.user.employee.photo.url}}" alt="" style="width: 40px; height: 40px;">
                        {% else %}
                        <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                        {% endif %}
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">{{request.user}}</h6>
                        <!-- <span>Admin</span> -->
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="{% url 'home' %}" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <a href="{% url 'leave' %}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Leave apply</a>
                    {% if user.employee.department_supervisor %}
                    <a href="{% url 'supervisor_leaves' %}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Your Staff Leave</a>
                    {% endif %}
                    {% if user.is_superuser %}
                    <a href="{% url 'employee' %}" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Employees</a>
                    <a href="/admin" class="nav-item nav-link"><i class="fa fa-table me-2"></i>View Admin</a>
                    {% endif %}
                    <a href="{% url 'profile' %}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Profile</a>
                    <a href="/logout" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Logout</a>
                    
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="{% url 'home' %}" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                {% if messages %}
                {% for message in messages %}
                <div class="search">
                <div class="alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}">
                    {{message}}
                </div>
                </div>
                {% endfor %}
                {% endif %}
            </nav>
            <!-- Navbar End -->


            {% block main %}
            {% endblock main %}

            

            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="https://ea-africaexchange.com">East Africa Exchange</a>, All Right Reserved. 
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            {% comment %} Designed By <a href="https://mutabarukajapheth.net.rw">Japheth & Aaron</a> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>

    {% block script %}
    {% endblock script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/employee.html
{% extends 'base.html' %}

{% block main %}
<!-- Navbar End -->
<!-- Table Start -->
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-white rounded h-100 p-4">
                <h6 class="mb-4">Employee List</h6>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">First Name</th>
                                <th scope="col">Last Name</th>
                                <th scope="col">Position</th>
                                <th scope="col">Phone Number</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for employee in employees %}
                            <tr>
                                <td>{{employee.user.first_name}}</td>
                                <td>{{employee.user.last_name}}</td>
                                <td>{{employee.position}}</td>
                                <td>{{employee.phone_number}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Table End -->


<!-- Footer Start -->
{% endblock main %}
          

templates/index.html
{% extends 'base.html' %}
{% block main %}
<!-- Sale & Revenue Start -->
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-6 col-xl-4">
            <div class="bg-white rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-line fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">{{card1_text}}</p>
                    <h6 class="mb-0 text-muted">{{card1_value}}</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-4">
            <div class="bg-white rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-bar fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">{{card2_text}} {% for leave in total_leave_type%}{{leave.leave_date}}{% endfor %}</p>
                    <h6 class="mb-0 text-muted">{{card2_value}}</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-4">
            <div class="bg-white rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-area fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">{{card3_text}}</p>
                    <h6 class="mb-0 text-muted">{{card3_value}}</h6>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Sale & Revenue End -->


<!-- Sales Chart Start -->
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-6">
            <div class="bg-white rounded h-100 p-4">
                <h6 class="mb-4">Single Line Chart</h6>
                <canvas id="line-chart"></canvas>
            </div>
        </div>
        <div class="col-sm-12 col-xl-6">
            <div class="bg-white rounded h-100 p-4">
                <h6 class="mb-4">Doughnut Chart</h6>
                <canvas id="doughnut-chart"></canvas>
            </div>
        </div>
    </div>
</div>
{% endblock main %}
<!-- Sales Chart End -->
{% block script %}
<script>
    (function ($) {
    "use strict";


    // Chart Global Color
    // Chart.defaults.color = "#6C7293";
    // Chart.defaults.borderColor = "#000000";


    

    // Single Line Chart
    var ctx3 = $("#line-chart").get(0).getContext("2d");
    var myChart3 = new Chart(ctx3, {
        type: "line",
        data: {
            labels: [{% for leave_day in total_month_leave %}'{{leave_day.leave_date.day}}', {% endfor %}],
            datasets: [{
                label: "Leaving in Months",
                fill: false,
                backgroundColor: "rgba(235, 22, 22, .7)",
                data: [{% for leave_day in total_month_leave %}'{{leave_day.leave_date__count}}', {% endfor %}]
            }]
        },
        options: {
            responsive: true
        }
    });


   

    // Doughnut Chart
    var ctx6 = $("#doughnut-chart").get(0).getContext("2d");
    var myChart6 = new Chart(ctx6, {
        type: "doughnut",
        data: {
            labels: [{% for leave_type in total_leave_type %}'{{leave_type.leave_type}}', {% endfor %}],
            datasets: [{
                backgroundColor: [
                    "rgba(235, 22, 22, .7)",
                    "rgba(245, 40, 145, 0.8)",
                    "rgba(143, 187, 139, 0.8)",
                    "rgba(143, 0, 255, 0.8)",
                    "rgba(0, 0, 255, 0.8)",
                    "rgba(0, 255, 255, 0.8)"
                ],
                data: [{% for leave_type in total_leave_type %}'{{leave_type.leave_type__count}}', {% endfor %}]
            }]
        },
        options: {
            responsive: true
        }
    });



    })(jQuery);
</script>

{% endblock script %}

templates/leave.html
{% extends 'base.html' %}
{% block main %}
<!-- Navbar End -->

<!-- Form Start -->
<div class="container-fluid pt-4 px-4">
    {% if request.user.employee %}
    
    <form method="post" class="row g-4">
        <div class="col-sm-12 col-xl-12">
            {% csrf_token %}
            <div class="bg-white rounded h-100 p-4">
                <h6 class="mb-4">Apply Leave</h6>
                <div class="form-floating mb-3">
                    <input type="date" name="leaving_date" class="form-control bg-white" id="floatingInput"
                        placeholder="name@example.com">
                    <label for="floatingInput">Leave date</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="date" name="returning_date" class="form-control bg-white" id="floatingPassword"
                        placeholder="Password">
                    <label for="floatingPassword">Returning date</label>
                </div>
                <div class="form-floating mb-3">
                    <select class="form-select bg-white" name="leave_type" id="floatingSelect"
                        aria-label="Floating label select example">
                        <option value="paid_leave">Paid leave</option>
                        <option value="sick_leave">Sick leave</option>
                        <option value="marternity_leave">Marternity leave</option>
                        <option value="parternity_leave">Parternity leave</option>
                        <option value="sabbatical_leave">Sabbatical leave</option>
                    </select>
                    <label for="floatingSelect">Leave with selects</label>
                </div>
                <div class="form-floating mb-3">
                    <textarea class="form-control bg-white" name="comment" placeholder="Leave a comment here"
                        id="floatingTextarea" style="height: 150px;"></textarea>
                    <label for="floatingTextarea">Comments</label>
                </div>
                <div class="m-n2">
                    <button type="submit" class="btn btn-primary m-2">Apply Leave</button>
                </div>
            </div>
        </div>
        
    </form>

    {% else %}
    <div class="bg-white rounded h-100 p-4">
        <h6 class="mb-4 text-dark">Sorry NO employee Assigned Yet</h6>
    </div>
    {% endif %}
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-white rounded h-100 p-4">
                <h6 class="mb-4">Applied Leaves</h6>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Leave Type</th>
                                <th scope="col">Leave Date</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for leave in leaves %}
                            <tr>
                                <td>{{leave.leave_type}}</td>
                                <td>{{leave.leave_date}}</td>
                                <td>{{leave.status}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Form End -->


<!-- Footer Start -->
{% endblock main %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<!-- Navbar End -->

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-white rounded h-100 p-4">
                <h6 class="mb-4">Profile</h6>
                <div class="owl-carousel testimonial-carousel">
                    <div class="testimonial-item text-center">
                        {% if employee.photo %}
                            <img class="img-fluid rounded-circle mx-auto mb-4" src="{{ employee.photo.url }}" style="width: 100px; height: 100px;">
                        {% else %}
                            <img class="img-fluid rounded-circle mx-auto mb-4" src="{% static 'img/testimonial-1.jpg' %}" style="width: 100px; height: 100px;">
                        {% endif %}
                        <h5 class="mb-1 text-primary"> {% if employee.user.username %}{{ employee.user.username }}'s Profile {% else %} NO employee assigned{% endif %}</h5>
                        <p>{{ employee.position }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-white rounded h-100 p-4">
                <h6 class="mb-4">Personal Information</h6>
                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill"
                            data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home"
                            aria-selected="true">Basic Detail</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill"
                            data-bs-target="#pills-profile" type="button" role="tab"
                            aria-controls="pills-profile" aria-selected="false">Attachment</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill"
                            data-bs-target="#pills-contact" type="button" role="tab"
                            aria-controls="pills-contact" aria-selected="false">Next of Keen</button>
                    </li>
                </ul>
                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                        <div class="col-sm-12 col-xl-12">
                            <div class="bg-white rounded h-100 p-4">
                                <table class="table table-borderless">
                                    <tbody>
                                        <tr>
                                            <th scope="row">1</th>
                                            <td>First Name</td>
                                            <td>{{ employee.first_name }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">2</th>
                                            <td>Last Name</td>
                                            <td>{{ employee.last_name }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">3</th>
                                            <td>Email</td>
                                            <td>{{ employee.user.email }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">4</th>
                                            <td>Phone Number</td>
                                            <td>{{ employee.phone_number  }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">5</th>
                                            <td>Gender</td>
                                            <td>{{ employee.get_sex_display  }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">6</th>
                                            <td>Position</td>
                                            <td>{{ employee.position}}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">7</th>
                                            <td>Hire Date</td>
                                            <td>{{ employee.hire_date}}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">8</th>
                                            <td>Department</td>
                                            <td>{{ employee.department}}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">9</th>
                                            <td>Date Of Birth</td>
                                            <td>{{ employee.date_of_birth}}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">10</th>
                                            <td>RSSB Number</td>
                                            <td>{{ employee.rssb_id }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                        <div class="col-sm-12 col-xl-6">
                            <div class="bg-white rounded h-100 p-4">
                                <table class="table table-borderless">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Attachment Name</th>
                                            <th scope="col">Attachment File</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for attachment in employee.attachments.all %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ attachment.attachment_name }}</td>
                                            <td><a href="{{ attachment.file.url }}">{{ attachment.file.url }}</a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
                        <div class="col-sm-12 col-xl-6">
                            <div class="bg-white rounded h-100 p-4">
                                <table class="table table-borderless">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">First Name</th>
                                            <th scope="col">Last Name</th>
                                            <th scope="col">Phone Number</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for keen in employee.next_of_keens.all %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ keen.next_of_keen_first_name }}</td>
                                                <td>{{ keen.next_of_keen_last_name }}</td>
                                                <td>{{ keen.next_of_keen_phone_number }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock main %}